version: '3.8'

services:
  web:
    build: .
    image: library-app:1.0.0
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    networks:
      - library-network
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    command: hypercorn app:asgi_app --bind 0.0.0.0:5000 --workers 4

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - library-network
    healthcheck:
      test: [
          "CMD",
          "mysqladmin",
          "ping",
          "-h", "localhost",
          "-u", "root",
          "--password=$${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

volumes:
  mysql_data:
    driver: local

networks:
  library-network:
    driver: bridge
    name: library-network
